hacker: false
name: "steve"
hobbies:
  - skateboarding
  - snowboarding
  - go
nums:
  - 2
  - 5
age: 20
server:
  host: "locahost"
  host_2: "local"
  port: ":8090"
  nestedList1:
    - 78
    - 90
  nestedList2:
    - 79
    - 22.0
  nestedList3:
    - mango
    - papaya
    - banana
  nestedList4:
    - 67